version: "3.8"

services:
  # pdf-generator:
  #   container_name: pdf-generator
  #   build:
  #     context: ../modules/pdf-generator
  #     dockerfile: ../../docker/Dockerfile.module.pdfgen
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   ports:
  #     - 86:5056
  #   # dns:
  #   #   - 192.168.10.1
  #   tty: true
  #   stdin_open: true
  #   restart: on-failure
  events:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: events-api
    build:
      context: ../app
      dockerfile: ../docker/Dockerfile.events.${ENV_MODE}
    # volumes:
    #   # - ../app/yarn.lock:/app/yarn.lock
    #   - ../app/node_modules:/app/node_modules
    # - ../app/workspaces/events/src/events:/app/workspaces/events/src/events
    env_file:
      - ../configs/.env
    ports:
      - 86:5056
    tty: true
    stdin_open: true
    restart: on-failure

  redis:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # network_mode: "host"
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - /db/redis/data:/data
    tty: true
    stdin_open: true
    restart: on-failure

  api:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # network_mode: "host"
    container_name: api-${ENV_MODE}
    build:
      context: ../app
      dockerfile: ../docker/Dockerfile.api.${ENV_MODE}
    # volumes:
    # - ../app/yarn.lock:/app/yarn.lock
    # - ../app/workspaces/events/src/events:/app/workspaces/events/src/events
    # - ../app/node_modules:/app/node_modules
    links:
      - "events"
    ports:
      - 85:5055
      - 5172:5172
      # - 1401:1401
      - 1420:1420
    env_file:
      - ../configs/.env
    tty: true
    stdin_open: true
    restart: on-failure
